Repository Wanted-Pre-Onboarding-Backend7-R/sns-feed-integration, pull requests merged in 2023-10, with the labels that each got.

#7 setup: 프로젝트 이름(아티팩트) 변경 #6
  settings.gradle
  src/main/java/com/wanted/teamr/skeleton/domain/SnsType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/SnsFeedIntegrationApplication.java
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/MemberController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/BaseEntity.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Member.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Post.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/PostHashtag.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/SnsType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/CustomErrorResponse.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/CustomException.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/GlobalControllerAdvice.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/MemberRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/test/java/com/wanted/teamr/snsfeedintegration/SnsFeedIntegrationApplicationTests.java
Labels: 🧹 setup

#9 feat #8: 시큐리티 필터체인 작성
  src/main/java/com/wanted/teamr/snsfeedintegration/security/SecurityConfig.java
Labels: ☁️ feature

#18 feat/#10 게시물 상세 조회 API 구현
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Post.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/PostHashtag.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/SnsType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/PostGetResponse.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/GlobalControllerAdvice.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceMockTest.java
  src/test/resources/application.yml
Labels: ☁️ feature

#19 사용자 회원가입 API 구현 완료 feat #11
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/MemberController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Member.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberJoinRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/CustomErrorResponse.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/CustomException.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCodeType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/GlobalControllerAdvice.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/RequestBodyErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/SecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/ApprovalCodeGenerator.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/PasswordValidator.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/ValidationGroup.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/ValidationSequence.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/TestConstants.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/MemberServiceTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/util/ApprovalCodeGeneratorTest.java
Labels: ☁️ feature

#24 fix #23: ErrorCode 콤마 빠진 것 추가
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
Labels: 🔨 fix

#15 feat: 게시물 좋아요 API 구현
  build.gradle
  src/main/java/com/wanted/teamr/snsfeedintegration/config/ExternalApiConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Post.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/SnsType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/SnsService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/WebClientService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/WebClientServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/external-api-config.yml
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceConcurrencyTest.java
  src/test/resources/application.yml
Labels: ☁️ feature

#27 사용자 가입승인 API 구현 완료 feat #22
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/MemberController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Member.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberApprovalRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberJoinRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/RequestBodyErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/MemberRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/ValidationGroup.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/ValidationSequence.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/TestConstants.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/MemberServiceMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/MemberServiceTest.java
Labels: ☁️ feature

#17 feat: jwt 설정 및 사용자 로그인 API 구현
  .gitignore
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/MemberController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Authority.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Member.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/RefreshToken.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/UserDetailsImpl.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberLogInRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/TokenDto.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/MemberRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/RefreshTokenRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/JwtSecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/SecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/UserDetailsServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceConcurrencyTest.java
  src/test/resources/application.yml
Labels: ☁️ feature

#28 feat: 게시물 공유 API 구현
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Post.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/SnsService.java
  src/main/resources/external-api-config.yml
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceConcurrencyTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceMockTest.java
Labels: ☁️ feature

#31 test #30: 시큐리티 설정 후 깨진 테스트 수리
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/JwtFilter.java
  src/main/java/com/wanted/teamr/snsfeedintegration/jwt/TokenProvider.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/JwtSecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/SecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/MemberServiceMockTest.java
Labels: 🧪 test

#35 feat: Security 설정 적용 후 게시물 공유, 좋아요 API 유저 관련 로직 추가 및 수정
  build.gradle
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Member.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/CurrentMember.java
  src/main/java/com/wanted/teamr/snsfeedintegration/security/SecurityConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/SnsService.java
  src/main/resources/application.yml
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerMockTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/fixture/JwtFixture.java
  src/test/java/com/wanted/teamr/snsfeedintegration/fixture/MemberFixture.java
  src/test/java/com/wanted/teamr/snsfeedintegration/security/WithAuthUser.java
  src/test/java/com/wanted/teamr/snsfeedintegration/security/WithAuthUserSecurityContextFactory.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceConcurrencyTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceMockTest.java
  src/test/resources/application.yml
Labels: 🔨 fix, ☁️ feature, 🧪 test

#20 feat/#14 통계 API 구현
  .gitignore
  build.gradle
  src/main/java/com/wanted/teamr/snsfeedintegration/config/QuerydslConfig.java
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/StatisticsController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/StatisticsType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/StatisticsValue.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/StatisticsGetRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/StatisticsGetResponse.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/RequestBodyErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostHashtagRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostHashtagRepositoryCustom.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostHashtagRepositoryImpl.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/StatisticsService.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/StatisticsControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/StatisticsServiceTest.java
  src/test/resources/db/statistics.sql
Labels: ☁️ feature

#38 refactor #34: `MemberService` 공통 로직 추출 및 불필요 코드 제거
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/AccountInfo.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberApprovalRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/MemberLogInRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/MemberService.java
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/MemberControllerTest.java
Labels: 🛠 refactor

#36 feat #26: 게시물 리스트 조회 API 구현
  src/main/java/com/wanted/teamr/snsfeedintegration/controller/PostController.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/Post.java
  src/main/java/com/wanted/teamr/snsfeedintegration/domain/SearchByType.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/PostGetResponse.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/PostSearchCondition.java
  src/main/java/com/wanted/teamr/snsfeedintegration/dto/PostSearchRequest.java
  src/main/java/com/wanted/teamr/snsfeedintegration/exception/ErrorCode.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostRepository.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostRepositoryCustom.java
  src/main/java/com/wanted/teamr/snsfeedintegration/repository/PostRepositoryImpl.java
  src/main/java/com/wanted/teamr/snsfeedintegration/service/PostService.java
  src/main/java/com/wanted/teamr/snsfeedintegration/util/PostSearchConditionConverter.java
  src/main/resources/application.yml
  src/main/resources/pageable-config.yml
  src/test/java/com/wanted/teamr/snsfeedintegration/controller/PostControllerTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/repository/PostRepositoryTest.java
  src/test/java/com/wanted/teamr/snsfeedintegration/service/PostServiceMockTest.java
  src/test/resources/application.yml
Labels: ☁️ feature
